# Project
version=4.7.9.1
group=com.evandev.remi
java_version=25

# Common
minecraft_version=26.2
mod_name=Reliable EMI
mod_author=evanbones
mod_id=remi
license=MIT
credits=ConcerroX, Kobber
description=A mod adding many configurable features to EMI!
minecraft_version_range=[26.2,)
neo_form_version=26.2-2

# Dependencies
semi_version_fabric=8945654
semi_version_neoforge=8945655
mixinextras_version=0.5.0
modmenu_version=20.0.3
yacl_version=3.9.7+26.2

# Fabric
fabric_version=0.161.0+26.2
fabric_loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# NeoForge
neoforge_version=26.2.0.88
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true